<a href="https://colab.research.google.com/github/sh-shrey/ML/blob/main/Random-Forest%20Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df= pd.read_csv('/content/drive/MyDrive/final - final_analysis - Sheet1.csv')

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
#define dependent variable
Y= df['Mood_prediction'].values
Y=Y.astype('int')
#define independent variables
X= df.drop(labels=['Mood_prediction'],axis=1)

In [ ]:
#split data into train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=20) 

In [ ]:
print(X_train.shape, Y_train.shape,Y_test.shape )

(15775, 13) (15775,) (3944,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
model = RandomForestClassifier(n_estimators = 30, random_state=10)

In [ ]:
model.fit(X_train, Y_train)
prediction_test = model.predict(X_test)
print(prediction_test)

[0 1 1 ... 0 0 0]


In [ ]:
model.predict(X_test)

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn import metrics
print("Accuracy= ", metrics.accuracy_score(Y_test,prediction_test))

Accuracy=  0.9723630831643002


In [ ]:
confusion_matrix(Y_test, prediction_test)

array([[2592,   60],
       [  49, 1243]])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,prediction_test))
print(classification_report(Y_test,prediction_test))
print(accuracy_score(Y_test, prediction_test))

[[2592   60]
 [  49 1243]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      2652
           1       0.95      0.96      0.96      1292

    accuracy                           0.97      3944
   macro avg       0.97      0.97      0.97      3944
weighted avg       0.97      0.97      0.97      3944

0.9723630831643002
